ip_forward: true
network_compression_threshold: 256
stats: be011944-8c74-4d17-a02f-dd1188301fa7
permissions:
  default:
  - skinsrestorer.playercmds
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  Danatelom:
  - admin
  ilyaprunov:
  - admin
servers:
  auth:
    motd: '&aОнлайн'
    address: localhost:25575
    restricted: false
  sur:
    motd: '&aОнлайн'
    address: localhost:25567
    restricted: false
timeout: 30000
listeners:
- query_port: 25565
  motd: '&cСервер загружается...'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - auth
  bind_local_address: true
  host: 54.37.126.66:25565
  max_players: 333
  tab_size: 60
  force_default_server: true
prevent_proxy_connections: false
player_limit: 333
online_mode: false
log_commands: false
disabled_commands:
- disabledcommandhere
- alert
- greload
- server
- end
connection_throttle: 0
