# Все ошибки, баги, предложения и прочее просьба писать на гитхабе 
issues: "https://github.com/Dimatert9/BungeeCord/issues"
help: "http://www.rubukkit.org/threads/137038/"
bot-filter-version: "3.3.5"

# Не используйте '\n', используйте %nl%
messages:
  prefix: "&b&lBot&d&lFilter"
  checking: "%prefix%&7>> &aОжидайте завершения проверки..."
  checking-captcha: "%prefix%&7>> &aВведите номер с картинки в чат"
  checking-captcha-wrong: "%prefix%&7>> &cВы ввели капчу неправильно, пожалуйста попробуйте ещё раз. У вас &a%s &c%s"
  successfully: "%prefix%&7>> &aПроверка пройдена, приятной игры"
  kick-many-checks: "%prefix%%nl%%nl%&cС вашего айпи замечена подозрительная активность%nl%%nl%&6Повторите попытку через 10 минут"
  kick-not-player: "%prefix%%nl%%nl%&cВы не прошли проверку, возможно вы бот%nl%&7&oЕсли это не так, пожалуйста повторите попытку"
  kick-country: "%prefix%%nl%%nl%&cВаша страна запрещена на серверве"
  kick-big-ping: "%prefix%%nl%%nl%&cУ вас очень высокий пинг, скорее всего вы бот"
  # Title%nl%Subtitle
  # Оставьте пустым, чтобы отключить( прм: CHECKING_TITLE = "" )
  # Отключение титлов может немного улучшить производительность
  checking-title: "&r&lBot&b&lFilter%nl%&aИдёт проверка"
  checking-title-sus: "&rПроверка пройдена%nl%&aПриятной игры"
  checking-title-captcha: " %nl%&rВведите капчу в чат!"
# Сколько игроков/ботов должно зайти за 1 минуту, чтобы включилась защита
# Рекомендуемые параметры когда нет рекламы: 
# До 150 онлайна - 25, до 250 - 30, до 350 - 35, до 550 - 40,45, выше - подстраивать под себя 
# Во время рекламы или когда токо, токо поставили защиту рекомендуется повышать эти значения
protection-threshold: 30
# Как долго активна автоматическая защита? В миллисекундах. 1 сек = 1000
protection-time: 120000
# Показывать ли онлайн с фильтра
show-online: true
# Сколько времени есть у игрока чтобы пройти защиту. В миллисекундах. 1 сек = 1000
time-out: 12700

# Включить или отключить GeoIp
geo-ip:
  # Когда работает проверка
  # 0 - Всегда
  # 1 - Только во время бот атаки
  # 2 - Отключить
  mode: 1
  # Откуда качать GEOIP
  # Меняйте ссылку если по какой-то причине не качается по этой
  # Файл должен заканчиваться на .mmdb или быть запакован в .tar.gz
  geoip-download-url: "http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  # Разрешённые странны
  allowed-countries: 
  - "RU"
  - "UA"
  - "BY"
  - "KZ"
  - "EE"
  - "MD"
  - "KG"
  - "AZ"
  - "LT"
  - "LV"
  - "GE"
  - "PL"

# Включить или отключить проверку на высокий пинг
ping-check:
  # Когда работает проверка
  # 0 - Всегда
  # 1 - Только во время бот атаки
  # 2 - Отключить
  mode: 1
  # Максимальный допустимый пинг
  max-ping: 350

# Включить или отключить проверку на прямое подключение
server-ping-check:
  # Когда работает проверка
  # 0 - Всегда
  # 1 - Только во время бот атаки
  # 2 - Отключить
  # По умолчанию отключено, по скольку работает не очень стабильно, во время сильных атак
  mode: 2
  # В течении какого времени можно заходить на сервер после получения мотд сервера
  cache-time: 12
  kick-message: 
  - "%nl%"
  - "%nl%"
  - "&cВы были кикнуты! Не используйте прямое подключение"
  - "%nl%"
  - "%nl%"
  - "&bДля того чтобы зайти на сервер:"
  - "%nl%"
  - "&71) &rДобавте сервер в &lсписок серверов."
  - "%nl%"
  - "&lНаш айпи &8>> &b&lIP"
  - "%nl%"
  - "%nl%"
  - "&72) &rОбновите список серверов. "
  - "%nl%"
  - "&oЧтобы его обновить нажмите кнопку &c&lОбновить &r&oили &c&lRefresh"
  - "%nl%"
  - "%nl%"
  - "&73) &rПодождите &c1-3&r секунды и заходите!"

# Настройка как именно будет работать защита
# 0 - Только проверка с помошью капчи
# 1 - Проверка на падение + капча
# 2 - Проверка на падение, если провалилась, то капча
protection:
  # Режим работы пока нет атаки
  normal: 2
  # Режим работы во время атаки
  on-attack: 1

# Настройка датабазы
sql:
  # Тип датабазы. sqlite или mysql
  storage-type: "sqlite"
  # Через сколько дней удалять игроков из датабазы, которые прошли проверку и больше не заходили
  purge-time: 14
  # Настройки для mysql
  hostname: "127.0.0.1"
  port: 3306
  user: "user"
  password: "password"
  database: "database"
